### ISSUE TITLE
"Couldn't reopen [file]"

### ISSUE THREAD

**Issue by iAmThatMichael** [DidUknowiPwn/T4M#1]
Caused by something in PatchSteamDRM(), address for the error message is triggered 0x5DBA24, the actual message is at 0x87E3CC

**Comment by momo5502** [comment]
0x5DBA24 is FS_FOpenFileReadForThread. PatchSteamDRM only replaces the .text section with the unencrypted data, doubt it can cause any error, but try commenting it out and see if it still occurs.

**Comment by iAmThatMichael** [comment]
Well commenting out the func breaks everything else as the addresses are dependent on that.

What I mean: Unhandled exception at 0x0047AF2D in CoDWaW.exe: 0xC0000005: Access violation reading location 0x0FFADBF1.
Caused by the ReallocateAssetPool function.

http://i.imgur.com/pdrALA5.png

Disabling that causes another crash _NoBorder, so something is up with the patch.

Edit: For some reason it's not occurring anymore....

Edit 2:
Running the game with fs_game set then initializing another mod, then starting a map doesn't cause it to crash.
Running the game w/o fs_game set then initializing a mod, then starting a map does cause it to crash.

**Comment by iAmThatMichael** [comment]
After a lot more testing I found the cause to be related to Visual Studio... if you're running with a debugger attached it'll cause it to fail there. Will test a bit more with others.

**Comment by iAmThatMichael** [comment]
The DRM patcher enabled with no debugger attached game runs fine.
Thanks game!

Source: ProGamerzFTW

Tested it myself, confirmed working.
