### ISSUE TITLE
help lol  (cannot build project missing files it looks like also)

### ISSUE THREAD

**Issue by swifty-tekno** [DidUknowiPwn/T4M#11]
cant even build it
i get these erros
![t4m errors](https://user-images.githubusercontent.com/68487146/107259281-b906b400-6a34-11eb-8ebb-10ee46be1c96.PNG)
thanks in advance

**Comment by iAmThatMichael** [comment]
inside of root/deps/ run gitrev.bat and it'll generate the buildnumber.h that's necessary

**Comment by swifty-tekno** [comment]
ok thx

**Comment by swifty-tekno** [comment]
also i saw a custom version of r41 that works for lan
does this work for lan also

**Comment by iAmThatMichael** [comment]
lan fixed/steam should be identical enough where the offsets didn't change I can't recall though, haven't seen anyone complain about it so yeah

this is all legacy anyway

**Comment by swifty-tekno** [comment]
that didnt work i got a file called lastrev.txt
containing  Unknown Revision

**Comment by swifty-tekno** [comment]
also i saw this in the r41 
	(// ↓ 这个造成服务器验证失败？) = this just translated  // ↓ This causes server verification to fail?
	//PatchT4_SteamDRM();
that was the error me and friend keep getting from the release on ugx

**Comment by swifty-tekno** [comment]
hey dude u there that  givrev.bat file does nothing except open and close instantly while making a txt file called lastrev.txt
 
what do i do

**Comment by iAmThatMichael** [comment]
make sure you have git installed in c directory or modify the batch file yourself OR make your own buildnumber.h with the 3 defines "COMMIT" as an int, "COMMIT_STR" as a string, "BUILDHOST" as a string

**Comment by momo5502** [comment]
You need to clone the repo. You downloaded it as zip, which does not work.

**Comment by swifty-tekno** [comment]
ah  using git?
i will look up how to do that im noob at this stuff trying to learn

thanks for you help guys
