### ISSUE TITLE
Increase maximum FoV

### ISSUE THREAD

**Issue by TheEnbyWitch** [DidUknowiPwn/T4M#2]
Yeah, I know I can do that myself with the source code, but Oculus Rift games run at 110 fov most of the time (using software like VorpX, you can even run games that weren't made for oculus rift).

**Comment by iAmThatMichael** [comment]
Sadly I don't have an OR to test on. I don't even know if WaW can even support the OR; or, even any sort of VR.

**Comment by TheApadayo** [comment]
we would have to hook into lots of the d3d9 calls in order to make it compatible with OR and I don't think that is exactly a priority right now.

**Comment by TheVania** [comment]
I believe he just simply wants the max FoV in the source code be increased from 90 to 110, as he's using third-party software to use the Rift.

**Comment by TheApadayo** [comment]
If you really want an fov of 110 set cg_fov to 90 and then use cg_fovscale to achieve the desired fov.
fov = cg_fov \* cg_fovscale

**Comment by iAmThatMichael** [comment]
I think fovscale would work better with VR anyway.

**Comment by TheEnbyWitch** [comment]
Already implemented a FoV scale based slider in my mod
