### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by ghost** [DidUknowiPwn/T4M#6]
It would be nice to have CI set up for this project.
I recommend AppVeyor because it's free for open source projects and supports Visual C++.

@DidUknowiPwn If you want, I can fork the project and add premake5 so you can build with multiple versions of Visual Studio (it's just premake5 vs2015 or similar)

**Comment by TheApadayo** [comment]
maybe when there's enough people interested in the project who can't build it on their own.  Also we don't exactly wan't anyone who can't build it themselves using it due to the early state of the project
