### ISSUE TITLE
R45 is latest binary, but source code builds into R41

### ISSUE THREAD

**Issue by ineedbots** [DidUknowiPwn/T4M#9]
It appears the last 4 revs are missing from the source code and it's features are missing; increased memory limit, mod_ex, etc.

**Comment by iAmThatMichael** [comment]
Yeah I noticed a while ago something was up but I have no idea if I can find the source I was working from, I'll let you know.

Edit: reason being I have a new PC and didn't transfer old drives and I've mixed some stuff up since then.

**Comment by iAmThatMichael** [comment]
updated I found the old project and added them now, compiled fine on vs19

**Comment by ineedbots** [comment]
Yep missing features are working with the build
